version: "3.3"

services:

  api:
    build:
      context: .
    image: backend
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-gw.rule=PathPrefix(`/`)"
      - "traefik.http.services.api-gw.loadbalancer.server.port=3000"

  # greeter:
  #   build:
  #     context: .
  #   image: backend
  #   env_file: docker-compose.env
  #   environment:
  #     SERVICES: greeter

  users:
    build:
      context: .
    image: backend
    env_file: docker-compose.env
    environment:
      SERVICES: users

  auth:
    build:
      context: .
    image: backend
    env_file: docker-compose.env
    environment:
      SERVICES: auth

  checkins:
    build:
      context: .
    image: backend
    env_file: docker-compose.env
    environment:
      SERVICES: checkin

  rooms:
    build:
      context: .
    image: backend
    env_file: docker-compose.env
    environment:
      SERVICES: room

  traefik:
    image: traefik:v2.4
    command:
      - "--api.insecure=true" # Don't do that in production!
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - 3000:80
      - 3001:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  default:
    external:
      name: physical-space-management

volumes:
  data:
